name: onbush
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  auto_route: ^8.0.3
  get_it: ^7.6.8
  logger: ^2.2.0
  flashy_tab_bar2: ^0.0.10
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  animate_do: ^3.3.4
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  another_flushbar: ^1.12.30
  intl_phone_number_input: ^0.7.4
  intl: ^0.19.0
  form_builder_validators: ^10.0.1

  crypto: ^3.0.3
  convert: ^3.1.1
  json_annotation: ^4.9.0

  http: ^1.2.2
  provider: ^6.1.2
  bloc: ^8.1.4
  fluttertoast: ^8.2.6
  modal_bottom_sheet: ^3.0.0
  connectivity_plus: ^6.0.4
  carousel_slider: ^5.0.0
  flutter_localizations:
    sdk: flutter
  pin_code_fields: ^8.0.1
  device_info_plus: ^10.1.2
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  go_router: ^14.6.2
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^27.2.5
  flutter_windowmanager_plus: ^1.0.1
  dartz: ^0.10.1
  cached_network_image: ^3.4.0
  share_plus: ^10.0.0
  webview_flutter: ^4.10.0
  isar: ^3.1.0+1
  uuid: ^4.5.1
  percent_indicator: ^4.2.4
  smooth_page_indicator: ^1.2.1
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  android_intent_plus: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1
  mockito: ^5.4.4
  mocktail: ^1.0.4


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/avatars/
    - .env


  fonts:
    - family: Roboto
      fonts:
        # - asset: google_fonts/
        - asset: google_fonts/Roboto-Regular.ttf
          style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
